### ISSUE TITLE
routes per module ?

### ISSUE THREAD

**Issue by quasiperfect** [ivantcholakov/starter-public-edition-4#31]
hi

how would you go for adding routes / module ?

in my situation every module can have multiple controllers and not always the controller name can be the route

thanks in advance for your response

**Comment by ivantcholakov** [comment]
TODO: To be examined in the future: https://github.com/Bigwebmaster/codeigniter-modular-extensions-hmvc

**Comment by ivantcholakov** [comment]
I must reopen this issue for not forgetting the research work that is to be done.

**Comment by ivantcholakov** [comment]
The idea in https://github.com/Bigwebmaster/codeigniter-modular-extensions-hmvc sounds complex for adaptation in this starter and I am not sure that I like it. Closing.
