### ISSUE TITLE
Modules and rURI

### ISSUE THREAD

**Issue by Exelord** [ivantcholakov/starter-public-edition-4#41]
I think that this function:
```
$this->uri->ruri_string()
```
should return something like:
```
/modules/controller/function
```

but it return only:
```
/controllers/function
```

This is intended effect or just a bug? In my opinion ruri should return all path without any routing, so here is something wrong.

If I am wrong please explain me.

**Comment by ivantcholakov** [comment]
It is intended. It is how HMVC code from its original source works, I keep backward compatibility.

**Comment by Exelord** [comment]
Is some solution for that? I need to get full ruri like /modules/controllers/function

**Comment by ivantcholakov** [comment]
No.
