### ISSUE TITLE
sugestion to alternative markdown parser

### ISSUE THREAD

**Issue by quasiperfect** [ivantcholakov/starter-public-edition-4#42]
https://github.com/erusev/parsedown
https://github.com/erusev/parsedown-extra

**Comment by ivantcholakov** [comment]
I think. it would be better to keep the current parser and additionally to get the new one. And within the configuration file common/config/parser_markdown.php with and option $config['markdown_implementation'] the parser to be used may be chosen.

**Comment by quasiperfect** [comment]
your choice i just wanted to give you the link to investigate :)

**Comment by ivantcholakov** [comment]
https://github.com/ivantcholakov/starter-public-edition-4/commit/ce4328592a3ad72fa631a84e806245d49cbf6357
