### ISSUE TITLE
code question

### ISSUE THREAD

**Issue by quasiperfect** [ivantcholakov/starter-public-edition-4#43]
in Registry class the function has 

```
public function has($key)
  {
    $key = (string)$key;

    if ($key != '' && array_key_exists($key, self::$data))
    {
      return TRUE;
    }

    return FALSE;
  }
```
could be rewritten as
```
  public function has($key)
  {
    $key = (string)$key;

    return $key !== '' && array_key_exists($key, self::$data);
  }
```
?

**Comment by ivantcholakov** [comment]
Agreed, make a pull request.

**Comment by quasiperfect** [comment]
to my shame i don't use git
i will install in weekend and try to understand how to do a pull request

any git client you want to recommend for windows ?

**Comment by ivantcholakov** [comment]
I use Netbeans and it has a plugin for git. It is convenient for me.
Also, GitHub advertises https://windows.github.com , but I have not need it. You may whether it is easier for you.

Whatever editor you use, make sure that it saves sources UTF-8 encoded, and the line endings are in Linux style.

I will hold implementation of this task, so you can test GitHub with it.

**Comment by ivantcholakov** [comment]
I did it.
