### ISSUE TITLE
Modules Helper problem

### ISSUE THREAD

**Issue by Exelord** [ivantcholakov/starter-public-edition-4#44]
Hi Ivan,
I found a problem with helpers in module folder.

I create structure like that:
-mymodule
--controllers
--helpers
---MY_new_helper.php

and when i try to load Ive got:
`
$this->load->helper('my_new_helper');
`

`
Unable to load the requested file: helpers/my_new_helper.php
`

I tested it with many combination of name of the helper and adding module name to the name like:
`
$this->load->helper('mymodule/my_new_helper');
`

when I load helper in module from APP folder everything works OK
-appfolder
--helpers
---MY_new_helper.php

`
$this->load->helper('new_helper');
`

Could you look at this?

**Comment by ivantcholakov** [comment]
I did a change that probably has not been implemented in the original HMVC code. Anyway, If you have your structure:
 
mymodule
--controllers
--helpers
---MY_new_helper.php

you may use

```php
$this->load->helper('new');
```

or $this->load->helper('MY_new'); , but the firsts suggestion is better.

**Comment by Exelord** [comment]
Yeah :D Now its works perfectly! I tested and viola. Helper is loaded from module :)
Great job!
