### ISSUE TITLE
CSRF problem

### ISSUE THREAD

**Issue by Exelord** [ivantcholakov/starter-public-edition-4#45]
Hi,
I noticed problem with CSRF protection. I set all settings correctly. I even use `form_open()` for adding CSRF hidden element. And... Key is added to the element, CSRF is writing to cookie but what is weird .. I can still refresh a sent form. I tested it also in your clean project and i noticed the same problem. 

hmm... Could you look at this?

**Comment by ivantcholakov** [comment]
http://www.codeigniter.com/userguide3/libraries/security.html?highlight=csrf#cross-site-request-forgery-csrf

$config['csrf_regeneration'] - Could you check this setting?

**Comment by ivantcholakov** [comment]
$config['csrf_regenerate'] = FALSE;
This is my setting and it is not in the same as it is in CodeIgniter. I prefer it this way. If I have a form that makes some POST AJAX requests (for example it may contain cascaded select boxes), then I afraid that the form would be set with an expired/old token and the form posting would fail. This is why CSRF token regeneration is off by default in this platform.

If there is no chance your forms to be affected by AJAX requests then you may set
$config['csrf_regenerate'] = TRUE;

**Comment by Exelord** [comment]
yep... it was that.
I dont use POST Ajax so far for sending forms so I rather turn on regenerate.
Thanks for good explanation and sorry for fake issue :( I'm trying help how i can.

**Comment by ivantcholakov** [comment]
No problem at all.
