### ISSUE TITLE
"Assets directory is not writeable"

### ISSUE THREAD

**Issue by Exelord** [ivantcholakov/starter-public-edition-4#46]
Hi,
I have a problem with non-mvc page. When I got to `/www/non-mvc/demo.php/` Ive got an error: `Assets directory is not writeable`. I checked permissions and I even set it to 777. Also I tested it on 2 different servers.

**Comment by ivantcholakov** [comment]
I don't see such an error. http://iridadesign.com/starter-public-edition-4/www/non-mvc/demo.php
Perhaps is comes from a customization?

**Comment by Exelord** [comment]
Yep, I checked again and it was my fault. Did u have integrated any library for minify css or js? You know... Application are modular so I extended it to have own module`s assets for each one. Every page can have different combinations of the modules so I made a library to combine css and js and include it to main HTML as one file. And here will be helpfull minify. Did you know some good libraries?

**Comment by ivantcholakov** [comment]
Unfortunately this is my weakness. I have no time researching and choosing the best one. At the moment I know this solution:

https://github.com/tonydewan/Carabiner

And there is a CMS that uses it:

https://github.com/srpurdy/SharpEdgeCMS

**Comment by Exelord** [comment]
Its a Good tool :+1:. I used some functionality and works prefect exactly as  I want.
But I noticed that assets loaded form eg.: (i use special controller to load it)

module
-assets
--img
---some-pic.png

is not caching. Is it can be problem with `.htaccess` file or with normal privileges to `platform` directory?

**Comment by ivantcholakov** [comment]
You are placing module-specific assets within a protected place. Everything that is under platform/ directory should not be accessed by the browser.

**Comment by Exelord** [comment]
hmm.. You have a right. It will be better to make good structure of assets folder and than just during install the module copy content of assets folder to right place.
