### ISSUE TITLE
Form_validation - is_unique[]

### ISSUE THREAD

**Issue by Exelord** [ivantcholakov/starter-public-edition-4#47]
Hi,
I noticed a problem with form_validation helper. When I set rule is_unique[users.email] I always get back FALSE as respond. Whatever I will type there always is FALSE. In config folder there also missing form_validation.php for settings some default options. Its not so much important but it can do nicely work :)

**Comment by ivantcholakov** [comment]
I don't like CodeIgniter's 'is_unique' rule, see CodeIgniter's issue 3109.
I use 'unique' rule that I have 'borrowed' from Bonfire. It is included within the platform, you can use it.

Sample code fragment:

```php
        $validation_rules = array(
            array(
                'field' => 'id',
                'label' => 'id',
                'rules' => 'trim'
            ),
            array(
                'field' => 'username',
                'label' => 'lang:ui_username',
                'rules' => 'nohtml|trim|required|min_length['.$this->users->username_min_length().']|max_length['.$this->users->username_max_length().']|callback__valid_username|callback__unique_username'
            ),
            array(
                'field' => 'email',
                'label' => 'lang:email',
                'rules' => 'nohtml|trim|required|valid_email|unique['.$this->users->table().'.email,'.$this->users->table().'.id]'
            ),
            array(
                'field' => 'first_name',
                'label' => 'lang:first_name',
                'rules' => 'nohtml|trim|required'
            ),
            array(
                'field' => 'last_name',
                'label' => 'lang:last_name',
                'rules' => 'nohtml|trim|required'
            ),
        );
```

Ignore the irrelevant to you things in code. $this->users->table() means the name of the users' table, you may hard-code it. The table has the field 'id' which is the primary key.

The important thing is that Bonfire's 'unique' rule does not give FALSE when a record is updated.

Here is code of the rule:

```php
    // The following rule has been "borrowed" from
    // Bonfire application starter, http://cibonfire.com/
    /**
     * Checks that a value is unique in the database.
     *
     * i.e. '…|required|unique[users.name,users.id]|trim…'
     *
     * <code>
     * "unique[tablename.fieldname,tablename.(primaryKey-used-for-updates)]"
     * </code>
     *
     * @author Adapted from Burak Guzel <http://net.tutsplus.com/tutorials/php/6-codeigniter-hacks-for-the-masters/>
     *
     * @param mixed $value  The value to be checked.
     * @param mixed $params The table and field to check against, if a second
     * field is passed in this is used as "AND NOT EQUAL".
     *
     * @return bool True if the value is unique for that field, else false.
     */
    public function unique($value, $params)
    {
        // Allow for more than 1 parameter.
        $fields = explode(',', $params);

        // Extract the table and field from the first parameter.
        list($table, $field) = explode('.', $fields[0], 2);

        // Setup the db request.
        $this->CI->db->select($field)
                     ->from($table)
                     ->where($field, $value)
                     ->limit(1);

        // Check whether a second parameter was passed to be used as an
        // "AND NOT EQUAL" where clause
        // eg "select * from users where users.name='test' AND users.id != 4
        if (isset($fields[1])) {
            // Extract the table and field from the second parameter
            list($where_table, $where_field) = explode('.', $fields[1], 2);

            // Get the value from the post's $where_field. If the value is set,
            // add "AND NOT EQUAL" where clause.
            $where_value = $this->CI->input->post($where_field);
            if (isset($where_value)) {
                $this->CI->db->where("{$where_table}.{$where_field} <>", $where_value);
            }
        }

        // If any rows are returned from the database, validation fails
        $query = $this->CI->db->get();
        if ($query->row()) {
            //$this->CI->form_validation->set_message('unique', lang('bf_form_unique'));
            $this->CI->form_validation->set_message('unique', $this->CI->lang->line('form_validation_is_unique'));
            return false;
        }

        return true;
    }
```

**Comment by Exelord** [comment]
Wow... Its a great solution. Nice and easy workaround :) a tested it and works perfectly.

**Comment by oghenez** [comment]
> I don't like CodeIgniter's 'is_unique' rule, see CodeIgniter's issue 3109.
> I use 'unique' rule that I have 'borrowed' from Bonfire. It is included within the platform, you can use it.
> 
> Sample code fragment:
> 
> ```
>         $validation_rules = array(
>             array(
>                 'field' => 'id',
>                 'label' => 'id',
>                 'rules' => 'trim'
>             ),
>             array(
>                 'field' => 'username',
>                 'label' => 'lang:ui_username',
>                 'rules' => 'nohtml|trim|required|min_length['.$this->users->username_min_length().']|max_length['.$this->users->username_max_length().']|callback__valid_username|callback__unique_username'
>             ),
>             array(
>                 'field' => 'email',
>                 'label' => 'lang:email',
>                 'rules' => 'nohtml|trim|required|valid_email|unique['.$this->users->table().'.email,'.$this->users->table().'.id]'
>             ),
>             array(
>                 'field' => 'first_name',
>                 'label' => 'lang:first_name',
>                 'rules' => 'nohtml|trim|required'
>             ),
>             array(
>                 'field' => 'last_name',
>                 'label' => 'lang:last_name',
>                 'rules' => 'nohtml|trim|required'
>             ),
>         );
> ```
> 
> Ignore the irrelevant to you things in code. $this->users->table() means the name of the users' table, you may hard-code it. The table has the field 'id' which is the primary key.
> 
> The important thing is that Bonfire's 'unique' rule does not give FALSE when a record is updated.
> 
> Here is code of the rule:
> 
> ```
>     // The following rule has been "borrowed" from
>     // Bonfire application starter, http://cibonfire.com/
>     /**
>      * Checks that a value is unique in the database.
>      *
>      * i.e. '…|required|unique[users.name,users.id]|trim…'
>      *
>      * <code>
>      * "unique[tablename.fieldname,tablename.(primaryKey-used-for-updates)]"
>      * </code>
>      *
>      * @author Adapted from Burak Guzel <http://net.tutsplus.com/tutorials/php/6-codeigniter-hacks-for-the-masters/>
>      *
>      * @param mixed $value  The value to be checked.
>      * @param mixed $params The table and field to check against, if a second
>      * field is passed in this is used as "AND NOT EQUAL".
>      *
>      * @return bool True if the value is unique for that field, else false.
>      */
>     public function unique($value, $params)
>     {
>         // Allow for more than 1 parameter.
>         $fields = explode(',', $params);
> 
>         // Extract the table and field from the first parameter.
>         list($table, $field) = explode('.', $fields[0], 2);
> 
>         // Setup the db request.
>         $this->CI->db->select($field)
>                      ->from($table)
>                      ->where($field, $value)
>                      ->limit(1);
> 
>         // Check whether a second parameter was passed to be used as an
>         // "AND NOT EQUAL" where clause
>         // eg "select * from users where users.name='test' AND users.id != 4
>         if (isset($fields[1])) {
>             // Extract the table and field from the second parameter
>             list($where_table, $where_field) = explode('.', $fields[1], 2);
> 
>             // Get the value from the post's $where_field. If the value is set,
>             // add "AND NOT EQUAL" where clause.
>             $where_value = $this->CI->input->post($where_field);
>             if (isset($where_value)) {
>                 $this->CI->db->where("{$where_table}.{$where_field} <>", $where_value);
>             }
>         }
> 
>         // If any rows are returned from the database, validation fails
>         $query = $this->CI->db->get();
>         if ($query->row()) {
>             //$this->CI->form_validation->set_message('unique', lang('bf_form_unique'));
>             $this->CI->form_validation->set_message('unique', $this->CI->lang->line('form_validation_is_unique'));
>             return false;
>         }
> 
>         return true;
>     }
> ```

Good solution, but has a bug. if the input data has a '.', it would give false errors
