### ISSUE TITLE
Integrating Facebook SDK

### ISSUE THREAD

**Issue by krishnaguragain** [ivantcholakov/starter-public-edition-4#51]
I want to integrate latest facebook login sdk 4, will you share me how to do.

**Comment by ivantcholakov** [comment]
I can't help on this now. I have to expand my authentication system, but I don't know when I would have the time.

http://stackoverflow.com/questions/23491666/how-to-use-facebook-sdk-4-0-0-with-codeigniter

**Comment by ivantcholakov** [comment]
I have just seen this http://forum.codeigniter.com/thread-61399.html

**Comment by krishnaguragain** [comment]
Thanx A lot.
I have make a facebook login library compatible with this, starter-public-edition .
If you need it , let me know i will share it.

![coithub](https://cloud.githubusercontent.com/assets/6104245/7204639/99ab8a3a-e543-11e4-9ab3-21cb92c3f75f.PNG)

**Comment by ivantcholakov** [comment]
Yes, I am interested.

**Comment by krishnaguragain** [comment]
Its on Github Now:-
https://github.com/krishnaguragain/Facebook-Plugin-For-Application-Starter-4

**Comment by ivantcholakov** [comment]
->set_canonical_url(site_url())
About the canonical URL - it is to be created for every page and it is different. site_url() is the home page of the site.

Thank you very much, at the beginning of the next week I will take your code and I will adapt it within the starter, with the correspondent attributions.

**Comment by ivantcholakov** [comment]
Done, v4.0.3.
