### ISSUE TITLE
Got a new Error

### ISSUE THREAD

**Issue by krishnaguragain** [ivantcholakov/starter-public-edition-4#53]
I got this error after the footer in latest release.
(below: - I have use database for session.)
![error1](https://cloud.githubusercontent.com/assets/6104245/7256532/70f010d2-e86f-11e4-9760-dc8c1a2109d6.PNG)

**Comment by ivantcholakov** [comment]
I tried the database driver, it works for me. I can't reproduce the error. Switch to 'files' driver.

**Comment by ivantcholakov** [comment]
@krishnaguragain

On the same computer, I see it is Windows, install pure CodeIgniter from the develop branch, activate Session with database driver and see whether this error would appear. I suspect that the field names after INSERT INTO are not escaped properly. If the same error appears, this bug should be reported to CodeIgniter.

What exactly is the database driver, mysql, mysqli, pdo?

**Comment by krishnaguragain** [comment]
@ivantcholakov Oops that was my session path and new session database mismatch.
And I am developing a User management System (Module)in this Starter public edition.If you have any idea or other special feature requirements then let me know.

**Comment by ivantcholakov** [comment]
Yes, user management system is a must, I think about an implementation. Also, most probably in the future I will apply this design to the admin site: https://github.com/almasaeed2010/AdminLTE , it is rich of features and it has a good license. But when this will happen, I can not promise.
