### ISSUE TITLE
Template

### ISSUE THREAD

**Issue by krishnaguragain** [ivantcholakov/starter-public-edition-4#54]
Can We have Different Template in Different Module. If So, How can we do it ??

**Comment by ivantcholakov** [comment]
Within the controller you are to write

```php
$this->template->set_layout('new_layout');
```

**Comment by ivantcholakov** [comment]
@krishnaguragain
Are you OK there?

**Comment by krishnaguragain** [comment]
@ivantcholakov I am just ok but it will take some more days to be in previous position.

**Comment by krishnaguragain** [comment]
@ivantcholakov Hi,
How can I check if admin(user) is logged in from one app and check it from another app.
 e.g In site_examples from admin_example.

**Comment by ivantcholakov** [comment]
What is the purpose of this, why do you need it?
I use independent logging pages in the front-end and in admin applications, the application sessions are different for better security.

**Comment by krishnaguragain** [comment]
like account.example.com where account is different app and i want to see whether the user is logged in or not from example.com (default app)

**Comment by ivantcholakov** [comment]
I understand it as  something like "Who is online". Here is a sample explanation on how it is could be done, the provided code is old, it should be reworked: http://www.plus2net.com/php_tutorial/whois-online.php

**Comment by krishnaguragain** [comment]
Finally I solved my problem by using flexi auth library in core codeigniter application(i.e inside common folder) and then call from any module or app then it works.
After few more days i will put it on github.

**Comment by ivantcholakov** [comment]
I will be capable to look at it in the beginning of June.

**Comment by krishnaguragain** [comment]
Hello.
@ivantcholakov Why the app cannot set session when the domain is like http://example only.but it works fine when the domain is http://example.com

**Comment by ivantcholakov** [comment]
For http://localhost session works, I don't see a reason why not.

**Comment by ivantcholakov** [comment]
With http://ivan session does not work, confirmed.

**Comment by ivantcholakov** [comment]
I've just proposed a correction, #57.
