### ISSUE TITLE
 Cannot access protected property...

### ISSUE THREAD

**Issue by Knight-Yoshi** [ivantcholakov/starter-public-edition-4#58]
Message: Cannot access protected property CI_Loader::$_ci_cached_vars

Filename: libraries/Template.php

Line Number: 981

I'm using CI3 and just the template library, I copied it into CI's normal library application/library directory and the template_helper into the application/helper directory and autoload both the library and the helper - (created and autoload a helper for the ci() alias to get around that). I already have an existing project that's using Foundation instead of Bootstrap, I'd like to simply add the template library to it if at all possible.

**Comment by ivantcholakov** [comment]
No, this library is not portable for now, sorry.
