### ISSUE TITLE
common and per app events

### ISSUE THREAD

**Issue by quasiperfect** [ivantcholakov/starter-public-edition-4#59]
hi

i want to define some common events and per appname events without creating a module for this
so i was thinking on creating a class in platform\common\libraries,platform\applications\appname\libraries

how would you do it ?

**Comment by ivantcholakov** [comment]
An application-wide customizable class for registering events is possible, yes, I like the idea. I have no time at the moment for an implementation. You can propose an implementation and in the next week I'll be able to look at it. Otherwise I'll do it, but I don't know when.

**Comment by ster** [comment]
hi, you can look at this one:  https://github.com/ericbarnes/CodeIgniter-Events

really easy to implement and run :)

**Comment by ivantcholakov** [comment]
I already have it. :-) The topic is about an extra-feature.

**Comment by quasiperfect** [comment]
i use a very custom variant of starter-public-edition-4
for my needs is enough to modify the existing library to load the events files from the hardcoded locations
i think is enough one event class for common and one per app
so i will create a events folder and file in common and in every app and if present load

**Comment by ivantcholakov** [comment]
I think, additional code in the released platform is not necessary. The goal can be achieved by creation of an "empty" module that contains only the file events.php.

```
application_name
    modules
        common_events
            events.php
            index.html (protection)
```

**Comment by quasiperfect** [comment]
the code is made to load the file named in a specific mode

so for 
platform\applications\site i have to create a module named site and the class Events_Site

platform\applications\manager i have to create a module named manager and the class Events_Manager

platform\common i have to create i have to create a module named common and the class named Common_Events_Common

and it seams to load only the events from common and "site" from manager it fails

so i will rewrite the events lib because i don't like this limitations

**Comment by ivantcholakov** [comment]
"
...
and it seams to load only the events from common and the application called so if i want o call a event defined in manager from site i can't

so i will rewrite the events lib because i don't like this limitations
...
"

I don't accept this idea and I am proposing you not to go there.

The applications are isolated, shared code should only be within the common "application", this is intentional. If a request bootstraps the front application and then takes code form "manager" application, then mess could appear, because code within "manager" assumes that exactly "manager" is initialized/bootstrapped (but the initialization is different generally).

**Comment by quasiperfect** [comment]
@ivantcholakov and about the class names ?wouldn't tokenizer be better for this (you could use any name you want for the class) ?

**Comment by ivantcholakov** [comment]
Class names could be arbitrary, whatever you want. Only there should no be name repetition/collision.

**Comment by quasiperfect** [comment]
@ivantcholakov i ment that the current events class forces the name to follow a pattern

i have created on function to scan and load events

the only rule is that you have to use a events folder instead of a events file

so you can have common/events/unlimited nr of events files
so you can have appname/events/unlimited nr of events files
so you can have appname/modules/events/unlimited nr of events files

```
private static function _scan_and_load_events()
{
    $ci = get_instance();

    $ci->load->helper('file');
    $ci->load->helper('directory');
    $ci->load->helper('common');

    $module_dirs = array();

    if (is_dir(APPPATH . 'events' . DIRECTORY_SEPARATOR))
    {
      $module_dirs[] = APPPATH . 'events';
    }

    $dir_map = directory_map(APPPATH . 'modules', 1);

    if (!empty($dir_map))
    {
      foreach ($dir_map as $key => $name)
      {
        if (strpos($name, '.') !== false)
        {
          continue;
        }

        if (is_dir(APPPATH . 'modules' . DIRECTORY_SEPARATOR . $name . 'events/'))
        {
          $module_dirs[] = APPPATH . 'modules' . DIRECTORY_SEPARATOR . $name . 'events';
        }
      }
    }

    if (is_dir(COMMONPATH . 'events' . DIRECTORY_SEPARATOR))
    {
      $module_dirs[] = COMMONPATH . 'events';
    }

    $dir_map = directory_map(COMMONPATH . 'modules', 1);

    if (!empty($dir_map))
    {
      foreach ($dir_map as $key => $name)
      {
        if (strpos($name, '.') !== false)
        {
          continue;
        }

        if (is_dir(COMMONPATH . 'modules' . DIRECTORY_SEPARATOR . $name . 'events/'))
        {
          $module_dirs[] = COMMONPATH . 'modules' . DIRECTORY_SEPARATOR . $name . 'events';
        }
      }
    }

    @ sort($module_dirs);

    if (!empty($module_dirs))
    {
      foreach ($module_dirs as $dir)
      {
        $events_files = get_filenames($dir, true);

        foreach ($events_files as $events_file)
        {
          if (pathinfo($events_file, PATHINFO_EXTENSION) === 'php')
          {
            $class = get_class_name($events_file);

            if ($class)
            {
              if (!class_exists($class, false))
              {
                include_once $events_file;

                if (class_exists($class, false))
                {
                  new $class;
                }
              }
            }
            else
            {
              log_message('error', 'Events error getting Class name for file :' . $events_file);
            }
          }
        }
      }
    }

    return true;
  }
```

and the common helper file taken from http://stackoverflow.com/questions/7153000/get-class-name-from-file

```
<?php defined('BASEPATH') OR exit('No direct script access allowed.');

if (!function_exists('get_class_name'))
{
  function get_class_name($file)
  {
    $fp = fopen($file, 'r');

    if ($fp)
    {
      $class = $buffer = '';
      $i = 0;

      while (!$class)
      {
        if (feof($fp))
        {
          break;
        }

        $tbuffer = fread($fp, 512);

        if ($tbuffer !== false)
        {
          $buffer .= $tbuffer;

          $tokens = token_get_all($buffer);

          if (strpos($buffer, '{') === false)
          {
            continue;
          }

          for (; $i < count($tokens); $i++)
          {
            if ($tokens[$i][0] === T_CLASS)
            {
              for ($j = $i + 1; $j < count($tokens); $j++)
              {
                if ($tokens[$j] === '{')
                {
                  $class = $tokens[$i + 2][1];

                  return $class;
                }
              }
            }
          }
        }
      }
    }

    return false;
  }
}
```

is the first draft so please give any type of feedback

**Comment by ivantcholakov** [comment]
On Monday evening I will have a closer look at the provided code.

**Comment by ivantcholakov** [comment]
@quasiperfect

Topics to be decided separately:

1- Add an ability for breaking the name conventions for classes that register event listeners.
2- As a sub-problem - Implement a common-purpose class-name retriever.
3- Implement special directory locations for classes that register event listeners.

-----------------------------------------------------

This can be implemented. But the current scanning mechanism should not be altered, I use it, there is no need for a compatibility break. An upgrade is possible, here is what I see for now:

1- The class name retriever to be implemented first as a function that could be placed in Core_Common.php and it to be available elsewhere, it is multi-purpose.

2- First upgrade of the Event library: Let a class to be tried to be detected by the current name convention. If the searched class does not exist, then use the file scanner to read the actual class name. Thus I can preserve performance of the current implementation.

3- Second upgrade of the Event library - add special locations for the classes that register event listeners. I am taking your suggestion about locations for consideration, the final decision could be postponed to when the time comes.

Is it ok?

**Comment by ivantcholakov** [comment]
For breaking the naming convention: Since the whole file is to be included anyway, the solution with using get_declared_classes() instead of tokenizer-based seems to me better.

**Comment by quasiperfect** [comment]
@ivantcholakov sounds good to me

not sure about get_declared_classes
with the tokenizer method you just read the beginning of the file 
with get_declared_classes you have to load the entire file, have to load the entire list of classes in memory twice, have to load the class definition in memory

we need to add a T_DOC_COMMENT remover to avoid a false positive if a class has a docblock with inline phpdoc comments /** bla bla {@see SomeClass} {@link http://example.com}

**Comment by ivantcholakov** [comment]
@quasiperfect
See my attempt to deforce the name convention. It seems to me nice.
https://github.com/ivantcholakov/starter-public-edition-4/commit/860f73a0ea01800bd9acf2f219777feb21cb02a1

**Comment by quasiperfect** [comment]
@ivantcholakov i will try to do some testing for speed vs options

**Comment by quasiperfect** [comment]
@ivantcholakov i done some testing and my version is faster (i added your constructor)

and you have the freedom of any name you want any nr of classes you want
the only difference is that my version imposes the events folder
```
 protected static $_listeners = array();

  protected static $_initialized = false;

  public function __construct()
  {
    if (!self::$_initialized)
    {
      self::_scan_and_load_events();
      self::$_initialized = true;
    }
  }
```

**Comment by quasiperfect** [comment]
@ivantcholakov i have retested and got mixed results i have to find some better method of testing

**Comment by ivantcholakov** [comment]
The idea for scanning a directory for php files and including them seems to me risky. I prefer loading files with particular names, that are determined by the system.

I think about adding more possible locations for events.php, let us say:
platform/applications/application_name/events.php
platform/common/events.php

This seems to me enough.

**Comment by quasiperfect** [comment]
@ivantcholakov that could work the only limit will be the nr of classes loaded

**Comment by ivantcholakov** [comment]
@quasiperfect

I've implemented the additional two file locations.

About the number of classes - in the centralized places they don't need to be many.

See one of the existing classes:

```php
<?php if (!defined('BASEPATH')) exit('No direct script access allowed');

/**
 * @author Ivan Tcholakov <ivantcholakov@gmail.com>, 2013
 * @license The MIT License, http://opensource.org/licenses/MIT
 */

class Common_Events_Email {

    protected $ci = null;
    protected $settings = null;

    public function __construct() {

        $this->ci = get_instance();

        $this->ci->load->library('settings');
        $this->settings = $this->ci->settings;

        if ($this->settings->get('mailer_enabled')) {

            Events::register('email', array($this, 'email'));
            Events::register('email_test', array($this, 'email_test'));
        }
    }

    public function email($data = array()) {

        return Modules::run('email/index', $data);
    }

    public function email_test($data = array()) {

        return Modules::run('email/test/index', $data);
    }

}
```

I just register the event, but I am moving their implementations in other places - module controllers, also modules or libraries can be used. Thus I am keeping the code here small - it is loaded at the initialization, it is good to be small.

In the centralized file if you do the same, you can register many listeners.

Ok for closing this task?

**Comment by ivantcholakov** [comment]
For directories... I can add a configuration option - an array with explicitly mentioned file names. Wait.

**Comment by ivantcholakov** [comment]
Yeah, this is it.
