### ISSUE TITLE
keep multilanguage but disable language segement in uri or method for translated uri's

### ISSUE THREAD

**Issue by quasiperfect** [ivantcholakov/starter-public-edition-4#60]
hi

is there a way to keep multilanguage but disable language segement in uri ?
or any suggestions on how to implement translated uri's

so would be possible to implement a config option to activate deactivate the automatic insertion of the language segment ?

i need to create something like this
site.com/en|es|it etc for any other language but default

the rest of urls i need to translate

site.com/contact (en)
site.com/contatto (it)
site.com/contacto (es)

this is for a cms

**Comment by ivantcholakov** [comment]
I will not do this:

site.com/контакт (bg)
site.com/контакт (ru)

Different languages have same words sometimes and according to your suggestion language detection would be unreliable.

And such an implementation involves over-engineering.
