### ISSUE TITLE
route question

### ISSUE THREAD

**Issue by quasiperfect** [ivantcholakov/starter-public-edition-4#61]
if you create a 'test' module with a 'test' controller with no index and no route you get a blank page instead of a 404

is this a bug or... ?

**Comment by ivantcholakov** [comment]
I can't say right now. I'll check this.

**Comment by ivantcholakov** [comment]
It is a bug, although not critical.

**Comment by ivantcholakov** [comment]
But I always see error 404, can't reproduce this.
