### ISSUE TITLE
PHP Startup: Unable to load dynamic library '/usr/lib/php5/20121212/msql.so

### ISSUE THREAD

**Issue by PrestonDocks** [ivantcholakov/starter-public-edition-4#63]
Running Apache 2, php 5.5.9 on Linux Mint 17

I get the following error on the home page (http://localhost/ci_test/www/)

A PHP Error was encountered

Severity: Core Warning

Message: PHP Startup: Unable to load dynamic library '/usr/lib/php5/20121212/msql.so' - /usr/lib/php5/20121212/msql.so: cannot open shared object file: No such file or directory

Filename: Unknown

Line Number: 0

Backtrace:

File: /var/www/html/ci_test/platform/common/core/Core_Exceptions.php
Line: 164
Function: include

File: /var/www/html/ci_test/platform/common/core/Common.php
Line: 263
Function: show_php_error

Mysql does work OK with other frameworks I have installed on this box (Nette and Composer)

**Comment by ivantcholakov** [comment]
I think you've got a typo somewhere in your PHP configuration. msql.so -> mysql.so

**Comment by PrestonDocks** [comment]
Thanks, just noticed that. Even so, I am not using msql so not sure why the framework would generate the errors. This is an out of the box setup. database.php is set to load mysqli driver.

So is this is a bug, or am I missing some configuration option.

**Comment by PrestonDocks** [comment]
Infact database is not setup in the autoload, so I'm not sure why any function would or should be looking for a database related extension.

**Comment by PrestonDocks** [comment]
OK. Problem fixed. I had to the follow the instructions at this link

http://askubuntu.com/questions/160947/why-isnt-the-mysql-extension-loading
