### ISSUE TITLE
Plans for 4.4

### ISSUE THREAD

**Issue by ivantcholakov** [ivantcholakov/starter-public-edition-4#64]
2015-11-13
-  ~~Preparation, 4.2.x: Introduce in this project CHANGELOG.md file.~~
- [x] Preparation, 4.2.x: Check against PHP7 (final) compatibility.
- [x ] The minimal required PHP version for the next major release would be ~~5.4~~ 5.5.0.
- [ ] ~~The next major release 4.4 will be based on CodeIgniter 3.2. Deprecated code/features in CodeIgniter 3.2 are to be preserved here as much as it is possible.~~
- [ ] ~~The transitional code that supports the old CI2 class/file naming convention is to be removed. 4.4 will support CI3 "ucfirst" class/file convention only.~~
- [ ] ~~Upgrade HMVC (https://bitbucket.org/wiredesignz/codeigniter-modular-extensions-hmvc) to version 5.5.~~
- [x] When it is applicable, the previously manually installed third party PHP components should be installed via Composer.
- [x] #31 
- [ ] ~~#56~~ 
- [x] The directories _www_ will be renamed into ~~_public_html_~~ public.
- [ ] ~~Bring automation in this project, adopt RoboTask PHP task runner,~~ https://github.com/Codegyre/Robo See this article: http://www.sitepoint.com/look-ma-no-nodejs-a-php-front-end-workflow-without-node/
- [ ] ~~The helper functions for web assets are to be reworked slightly for supporting automatically installed web assets.~~
- [x] Purge all Bootstrap 3 oriented web assets. Purge all web assets and PHP code oriented on support of old browsers.
-  ~~Adopt Bootstrap 4 (https://github.com/twbs/bootstrap) stable release. Update or rework third-party web assets so they could be compatible with Bootstrap 4.~~
- ~~Adopt AdminLTE 3, https://github.com/almasaeed2010/AdminLTE~~
- [ ] ~~Make a MySQL database for this project. Whether it would be a direct MySQL dump or a CodeIgniter's migration is a subject of a later decision.~~
- [ ] ~~Develop a simple administration panel that supports user management.~~
- [ ] ~~Develop a Semantic UI based simple front-end.~~

2015-11-14
- [ ] ~~Satelite projects (codeigniter-phpmailer, MY_Model): Drop support for CodeIgniter 2.~~
- [x] CodeIgniter, the system files: Move the customizations within outside, separate files.
- [x] CodeIgniter: Consider automatic upgrades via Composer (done).
-  ~~Proposed by @buoncri: Integrate Grocery CRUD (https://github.com/scoumbourdis/grocery-crud). Ivan: Throw away the current old-looking visual theme, develop A Bootstrap 4 based and MIT-licensed visual theme for Grocery CRUD.~~

2015-11-18
-  ~~Replace or convert all the styling sources from less to scss.~~

2015-12-03
- [ ] ~~Watch the Accelerated Mobile Pages Project, https://www.ampproject.org, https://github.com/ampproject/amphtml See whether and how it could be integrated.~~

2016-01-05

Implement more complex parsers / template engines:
- [x] Lex (that is used by PyroCMS, but implementation would not be the same, compatibility would be partial);
- [x] Twig;
-  ~~Blade, if it is possible.~~

2016-02-08
- [x] Consider [Semantic UI](http://semantic-ui.com) as an alternative to Bootstrap.

2016-02-10
- ~~Plates parser, http://platesphp.com~~

2016-02-26
- ~~Foil, PHP template engine for native PHP templates, https://github.com/FoilPHP/Foil~~

2016-06-08
- [ ] ~~Cron Task Scheduler~~

---

The list is not final, it could be extended or changed over the time. There is no a deadline for all these goodies. Suggestions and objections about this plan are welcome.

**Comment by buoncri** [comment]
:+1:  :+1: :+1:

**Comment by ivantcholakov** [comment]
@buoncri Included, I'll see what I can do about Grocery CRUD.

**Comment by ivantcholakov** [comment]
#67

**Comment by krishnaguragain** [comment]
Can we Implement [Aauth](https://github.com/emreakay/CodeIgniter-Aauth) to this project if i send PR Request as it have very rich in features ?

**Comment by ivantcholakov** [comment]
@krishnaguragain

No, I don't want it. If there is authentication in this project, it would br made by me.

**Comment by ivantcholakov** [comment]
[facebook-sdk-codeigniter](https://github.com/darkwhispering/facebook-sdk-codeigniter) library is going to be removed, because it is not maintained by its author anymore.

**Comment by krishnaguragain** [comment]
@ivantcholakov Sure, I am developing new version of it. I will send PR when it's finished.

**Comment by ivantcholakov** [comment]
https://symfony.com/blog/introducing-webpack-encore-for-asset-management
