### ISSUE TITLE
Where is "Support for database stored settings (Settings library)." database?

### ISSUE THREAD

**Issue by quangpd** [ivantcholakov/starter-public-edition-4#65]
Hi Ivan,

Where is "Support for database stored settings (Settings library)." database?

Thank you.

**Comment by quangpd** [comment]
Can you implement something like Settings Module base on Module, Theme to separate configs store  in DB

**Comment by ivantcholakov** [comment]
This is the library Settings that is supposed to be used by a programmer: https://github.com/ivantcholakov/starter-public-edition-4/blob/v4.0.106/platform/common/libraries/Settings.php

This library uses internally a model https://github.com/ivantcholakov/starter-public-edition-4/blob/v4.0.106/platform/common/models/Settings_model.php you don't have to use it directly in your code. It contains within a comment the structure of the database table that you have to create:

```php
/**
 * Create a table with the following sample definition:
 *
 * CREATE TABLE IF NOT EXISTS `settings` (
 *   `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
 *     `name` varchar(255) NOT NULL,
 *   `value` varchar(511) DEFAULT NULL,
 *   PRIMARY KEY (`id`),
 *   KEY `name` (`name`)
 * ) ENGINE=InnoDB  DEFAULT CHARSET=utf8;
 */
```

Make a database, connect your system to it, create the table 'settings', and in your code use the libraly Settings.
