### ISSUE TITLE
$this->uri->segments() should not return the language segment.

### ISSUE THREAD

**Issue by ivantcholakov** [ivantcholakov/starter-public-edition-4#66]
This is a change that I am going to implement for releases 3.0.112 and 4.0.112.

The language segment should not be returned by:

$this->uri->segment()
$this->uri->segment_array()
$this->uri->total_segments()

Rationale:

There is an option about hiding the URI-segment of the default language. But when this option is changed in an already built system, the indexes of the targeted other segments will change, and code will not work correctly.

Till this moment I avoided this problem by using $this->uri->rsegment(), but this was not the conceptual solution.

The URI language segment is needed only for language detection, for other aspects it should be "invisible".

**Comment by ivantcholakov** [comment]
Done.

**Comment by quasiperfect** [comment]
@ivantcholakov  wish i had a like button :)
