### ISSUE TITLE
db question

### ISSUE THREAD

**Issue by quasiperfect** [ivantcholakov/starter-public-edition-4#67]
hi

i need to save some config options to the database (with caching)
what is the earliest place (file position etc) i could use the database to load those options (in case the cache file doesn't exist)

thanks in advance for your help

unrelated (Plans for 4.1)
any chance to import some nice things from sprintphp ( https://github.com/ci-bonfire/Sprint )
in the order of importance (for me)
Email Queue system allows for very flexible email generations and sending.
Simple, GUI-less cron controller that can be used through standard crontab or scheduled tasks.
Database Seeding with CLI tool
The Forge - a code builder with simple generators in place, but fully customizable and easy to add your own.

**Comment by ivantcholakov** [comment]
I had a look at database caching in the past and I saw that there is no an implemented way to determine when and which cached files has been expired and to refresh them. This is why I lost interest in database caching. I can not help you with that.

**Comment by quasiperfect** [comment]
no you misunderstood me i was asking only for the earliest place where i could use the database

**Comment by ivantcholakov** [comment]
See this model https://github.com/ivantcholakov/starter-public-edition-4/blob/v4.0.119/platform/common/models/Settings_model.php Use the sample SQL in the comment to create the table for setting within your database.

After that in your application you can use the library Settings: https://github.com/ivantcholakov/starter-public-edition-4/blob/v4.0.119/platform/common/libraries/Settings.php

**Comment by ivantcholakov** [comment]
Oh, I got the meaning of this question.

https://github.com/ivantcholakov/starter-public-edition-4/blob/v4.0.150/platform/create.php#L490 - this seems to me the earliest place for common purpose.

I use database in an earlier place within the router for processing slugs, but a separate connection gets open. Refactoring is needed.

---------------------------------------------------------------------------------------

TODO:
Invent a way to open the default database connection earlier than CodeIgniter does that. Avoid duplication of the default connection. Test and mark within the source the earliest place.

**Comment by ivantcholakov** [comment]
At the moment I think about introducing the following function:

```php
function & get_gb_instance($group = null) // $group = null means the default connection.
{
    ...
}
```

Internally this function should contain a registry with the created classes for not creating implicitly duplicate connections.

**Comment by ivantcholakov** [comment]
get_db_instance() can be called after the benchmark timer initialization.

**Comment by ivantcholakov** [comment]
@quasiperfect

https://github.com/ivantcholakov/starter-public-edition-4/commit/5b8a5cb12cceff40ede2fa9d0b7908343afeb47d
