### ISSUE TITLE
Deleting Cache Dir

### ISSUE THREAD

**Issue by krishnaguragain** [ivantcholakov/starter-public-edition-4#69]
How to clean cache dir ??

**Comment by ivantcholakov** [comment]
Which derectory?

**Comment by krishnaguragain** [comment]
/platform/writable/

**Comment by ivantcholakov** [comment]
Manually delete the subdirectories. On Linux if as a current user you can't delete the subdirectories then open the directory 'writable' as a root user, Ubuntu has in its context menu the option "Open as root".

Don't delete the files index.html and .htaccess

Deletion is to be done before uploading the prepared site to the production server. On the first new request the necessary subdirectories will be created automatically.

Don't delete the directory 'platform/writable' itself, only make sure it is writable. Delete the subdirectorues.

**Comment by krishnaguragain** [comment]
Is there any code to delete the directories of platform/writable.

**Comment by ivantcholakov** [comment]
Code that deletes everything... no, and there would not be.
