### ISSUE TITLE
different language for applications

### ISSUE THREAD

**Issue by quasiperfect** [ivantcholakov/starter-public-edition-4#70]
hi

how would you go enabling 2 languages for site and only one language (is one of the 2 from site) for admin ?

example : site in english and italian and admin only english

**Comment by ivantcholakov** [comment]
Do you really need this?

**Comment by ivantcholakov** [comment]
Within platform/applications/admin/config/config.php (create it if it doesn't exist) add
$config['language'] = 'english';
Don't implement a language switcher within the admin panel and there will be only one language there.

**Comment by quasiperfect** [comment]
thanks for responding

yes someone asked for that configuration (i know is not logical)

i will give it a try and let you know
