### ISSUE TITLE
multiple applications

### ISSUE THREAD

**Issue by CodeXmonk** [ivantcholakov/starter-public-edition-4#72]
Hello Ivan, congrat your great work! It helps me a lot to learn CI3...

Untill I can find my own answers, would you tell me how multiple applications can be used?
What I mean: are they totally separated, or for instance: if I have one login module in one of the apps and someone is logged in using that module, is it possible for the other app to check the logged in state or I need another login module for the second app, so the two login mechanism is totally different from eachother?
Thank you for your answer and for your brilliant work!
Joey (codexmonk)

**Comment by ivantcholakov** [comment]
Hello,

Both of the two choices are possible, it depends on whether the two applications share or not the same session.

For example, as a result of the following settings, sessions of the front site and the admin site are independent, this is what I usually want:
https://github.com/ivantcholakov/starter-public-edition-4/blob/v4.0.133/platform/applications/site_example/config/config.php#L5
https://github.com/ivantcholakov/starter-public-edition-4/blob/v4.0.133/platform/applications/admin_example/config/config.php#L5

I these session identificators are the same, then login pages in the front and the admin might be made to login a user in both of the sites. Of course, in the admin application login should be somehow restricted only for administrators.

**Comment by CodeXmonk** [comment]
Thank you for your quick answer! I really appreciate your help... I will try...
