### ISSUE TITLE
Cache Issue

### ISSUE THREAD

**Issue by krishnaguragain** [ivantcholakov/starter-public-edition-4#75]
Hello @ivantcholakov ,
Currently i am doing one project on it. When I have added data from back-end(administrative) panel , data is successfully submitted to database but mean while reading from the database due to cache in platform/writable (WRITABLEPATH) it is not showing over browser, Please help me here how to turn off all those cache.
CI_VERSION = 3.0.6
PLATFORM_VERSION = 4.0.128

**Comment by ivantcholakov** [comment]
I don't understand the case. Could you explain it with more details?

**Comment by krishnaguragain** [comment]
I mean that due to cache written in /platform/writtable/ the exact data
from database is not rendered/display in browser although database is
updated.
Please do let me know how to turn off those cache.

**Comment by ivantcholakov** [comment]
You did not tell me anything new.

The starter contains "site_example" application that has only a login for and a landing page. There is no code that works with database at all. So, you or somebody else created this admin panel, how can I guess what is going on within it.

* /platform/writtable/ caches different things under subfolders, which one contains the old data or view?
* Do you use a template engine, Twig for example, or you use plain PHP for the views?
* What kind of old data is cached - database query results or rendered templates?
* Where you see the old cached data - within the admin panel or within the fornt-end? If you open the browser development tools, what kind of response code do you get - 200, 307 or something else?

This is what I can say so far.

**Comment by ivantcholakov** [comment]
Send me a private email at ivantcholakov@gmail.com
