### ISSUE TITLE
Sub-dropdown

### ISSUE THREAD

**Issue by krishnaguragain** [ivantcholakov/starter-public-edition-4#76]
The sub drop-down menu appears like this. Do you know how to fix this.
![menu_issue](https://cloud.githubusercontent.com/assets/6104245/20029200/3d413d36-a36e-11e6-9ac5-c255d9bad5fd.PNG)

**Comment by ivantcholakov** [comment]
v. 4.2.0 is still in development state, when the final release comes it will be free from such visual glitches. I also don't like the main menu as it is now. I will probably replace it.

**Comment by krishnaguragain** [comment]
Ok thanks. Currently i have adopt this one temporarily. [https://github.com/edomaru/codeigniter_multilevel_menu/](https://github.com/edomaru/codeigniter_multilevel_menu/)

**Comment by ivantcholakov** [comment]
@krishnaguragain

I think, the main menu is better now.

Menu items are rendered twice, there are a version for tablet/computer and a separate mobile version. It is a complication, but at least it gives more control on the appearance.
