### ISSUE TITLE
Error while setting setting's key & value

### ISSUE THREAD

**Issue by krishnaguragain** [ivantcholakov/starter-public-edition-4#77]
I got this error while using `$this->settings->set('theme_name','admin_default');`
![capture](https://cloud.githubusercontent.com/assets/6104245/22887346/d27bd014-f229-11e6-9ddf-3e802427a0ca.PNG)

Am I wrong or the code ??

**Comment by ivantcholakov** [comment]
If you want to store settings, you must have a connected database that contains the table 'settings', see the comments here:  https://github.com/ivantcholakov/starter-public-edition-4/blob/v4.2.38/platform/common/models/Settings_model.php

If this explanation is not enough, you have access to my unpublished CMS, check how storing settings is implemented there, in the administration panel.

**Comment by krishnaguragain** [comment]
I have connected database too and configured accordingly in Settings_model too but it doesn't work.
And i have checked to the unpublished cms but there is working smoothly and i don't find what makes it work in cms and not in this starter edition.

**Comment by ivantcholakov** [comment]
https://github.com/ivantcholakov/starter-public-edition-4/blob/v4.2.38/platform/applications/front/config/database.php

The demo database settings... remove them. https://github.com/ivantcholakov/starter-public-edition-4/blob/v4.2.38/platform/applications/front/config/database.php
Delete this file.

**Comment by ivantcholakov** [comment]
I did a test, it works for me. I can't guess what are you doing. I've prepared a clean application skeleton, without the demo code, so, you can try it.

Take this file, uncompress and install it.
https://drive.google.com/open?id=0BwlVg_yQ8MHBbDhqUFExcjJQY3M

Import the file on the root directory starter_test.sql within your MySQL server into a newly created database 'starter_test'.

Open the file platform/common/config/database.php and adjust there the connection settings for the newly created database.

Just for knowing, open the file platform/common/config/autoload.php You would see that within $autoload['libraries'] setting 'database' entry has been added by me.

Open the welcome (home) page of the site. On the page you will see a test with your example that works.

**Comment by krishnaguragain** [comment]
Ok it works now.
It was missing the database autoloading. 😄
