### ISSUE TITLE
Install using composer

### ISSUE THREAD

**Issue by ericariyanto** [ivantcholakov/starter-public-edition-4#78]
Hello mr @ivantcholakov , i think this is best codeigniter's customs so far. And i plan to use this for my next projects. This projects is updated frequently, so i think this project (starter public edition 4) is good if we can install from composer, so if there are an update, we just use composer update. So, can i ask you to make it available on composer?

Regards

NB : sorry for my bad english

**Comment by ivantcholakov** [comment]
No. it is too complex for that. Also, this project is far away from that kind of perfectness that would be suitable for Composer.

I am planning gradually to reduce the frequency of updates after CodeIgniter 3.1.4 is out, so you not to be forced to make updates manually too often. Now I am in the mood only for bug-fixing and external Composer-driven component updates.

A relatively big change for new projects will occur after CodeIgniter 3.2.0 gets released, but I can not say when exactly this will happen.

I am sorry for the inconvenience, but I have no the time to invent and to support a Composer-updated site skeleton.

**Comment by ericariyanto** [comment]
Ok, no problem. Many thanks for your response and explanations.
