### ISSUE TITLE
composer packages explication / question

### ISSUE THREAD

**Issue by quasiperfect** [ivantcholakov/starter-public-edition-4#79]
hi @ivantcholakov 

can you please specify what each package dose (some are clear) and if it's absolutely required ?

**Comment by ivantcholakov** [comment]
I have no time for a complete answer. Briefly:

"facebook/php-sdk-v4" : "~5.0" - this package I intend to purge in the near future, it is used by an abandoned library which I intend to remove too.

The other ones - they are used, keep them. If the volume of the vendor/ directory is your concern, reinstall the packages using the --no-dev option.

**Comment by ivantcholakov** [comment]
@quasiperfect

I've put a section about the packages within README.md. https://github.com/ivantcholakov/starter-public-edition-4/commit/384a3989d1871514bebc2a44acfecfba0548b777

If there is something unclear you may reopen this task.
