### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by ivantcholakov** [ivantcholakov/starter-public-edition-4#80]
Here I intend to collect some visual ideas.

**Comment by ivantcholakov** [comment]
![screenshot from 2017-12-13 12-38-25](https://user-images.githubusercontent.com/1438104/33935808-e277d9ac-e005-11e7-95d5-fdcd36f3c285.png)

**Comment by ivantcholakov** [comment]
![screenshot from 2017-12-13 13-11-39](https://user-images.githubusercontent.com/1438104/33936516-7f1a28e4-e008-11e7-9c86-fb7bb7b706fe.png)

**Comment by ivantcholakov** [comment]
![screenshot from 2017-12-17 20-22-19](https://user-images.githubusercontent.com/1438104/34082544-0b20784e-e369-11e7-94ba-556aeebb801d.png)

**Comment by ivantcholakov** [comment]
![screenshot from 2017-12-17 20-55-19](https://user-images.githubusercontent.com/1438104/34082803-095ecfc4-e36e-11e7-8f2d-c433c4b926ab.png)

**Comment by krishnaguragain** [comment]
Wow,
It's better to have screenshots in English language.

**Comment by ivantcholakov** [comment]
![screenshot from 2019-01-08 04-44-49](https://user-images.githubusercontent.com/1438104/51435751-bf783680-1c87-11e9-889b-a3b804aa851f.png)

**Comment by ivantcholakov** [comment]
@krishnaguragain I am sorry, that there are no screen-shots in English, this was a complex real project (a university campus management system - applications for rating, accommodation, rents and other fees, payments, reporting, etc.) in Bulgarian only. In the future for its public part maybe English language will be added.

**Comment by ivantcholakov** [comment]
![Screenshot from 2019-08-13 06-48-24](https://user-images.githubusercontent.com/1438104/63066188-9401b580-bf11-11e9-97a2-f09a79122111.png)
![Screenshot from 2019-08-15 03-59-17](https://user-images.githubusercontent.com/1438104/63066211-a4b22b80-bf11-11e9-9f87-2060ed317ed1.png)

**Comment by ivantcholakov** [comment]
![Screenshot from 2019-09-03 19-41-43](https://user-images.githubusercontent.com/1438104/64192743-0cf68c00-ce84-11e9-8ad6-868d716b2e7c.png)

**Comment by ivantcholakov** [comment]
![Screenshot from 2019-09-04 08-10-26](https://user-images.githubusercontent.com/1438104/64227400-fa17a200-ceeb-11e9-8822-35aa0b809380.png)

**Comment by ivantcholakov** [comment]
![Screenshot from 2019-09-06 00-45-31](https://user-images.githubusercontent.com/1438104/64387170-d8313300-d043-11e9-943f-929ae32cabd2.png)

**Comment by ivantcholakov** [comment]
![Screenshot from 2019-12-25 06-35-52](https://user-images.githubusercontent.com/1438104/71432594-509b2d00-26e3-11ea-9070-fdf8037fdc90.png)

**Comment by ivantcholakov** [comment]
A fiscal printer informative page.

![image](https://user-images.githubusercontent.com/1438104/73170142-5632cb00-4106-11ea-85d6-661fb66e4ea0.png)

**Comment by ivantcholakov** [comment]
![image](https://user-images.githubusercontent.com/1438104/80723901-de5fac80-8b09-11ea-9519-6059a21faf28.png)

**Comment by ivantcholakov** [comment]
![image](https://user-images.githubusercontent.com/1438104/80779640-ee60a600-8b74-11ea-8488-707dfff94107.png)

**Comment by ivantcholakov** [comment]
Corrections.
![project-kitchen](https://user-images.githubusercontent.com/1438104/80941725-da72a980-8deb-11ea-9f44-5d128da3c578.png)

**Comment by ivantcholakov** [comment]
![image](https://user-images.githubusercontent.com/1438104/81462977-d74a3580-91be-11ea-8c2a-9b5ef0117c66.png)

**Comment by ivantcholakov** [comment]
![image](https://user-images.githubusercontent.com/1438104/81473931-c7584300-920a-11ea-85b5-a00ee2306b99.png)

**Comment by ivantcholakov** [comment]
![image](https://user-images.githubusercontent.com/1438104/81487445-7590d680-9265-11ea-9b07-ce0bee336d02.png)

**Comment by ivantcholakov** [comment]
![Screenshot from 2020-06-13 14-07-30](https://user-images.githubusercontent.com/1438104/84567621-8790f800-ad82-11ea-82bf-4052b219e59f.png)

**Comment by ivantcholakov** [comment]
![Screenshot from 2020-06-14 08-04-42](https://user-images.githubusercontent.com/1438104/84585287-f750c280-ae16-11ea-981b-847dd6c771f7.png)

**Comment by ivantcholakov** [comment]
![image](https://user-images.githubusercontent.com/1438104/86201317-e36fc500-bb67-11ea-8d29-88d4ba46137a.png)

![image](https://user-images.githubusercontent.com/1438104/86201346-f84c5880-bb67-11ea-9d30-358f995cc329.png)

**Comment by ivantcholakov** [comment]
![image](https://user-images.githubusercontent.com/1438104/99946056-67785280-2d7e-11eb-8b24-83df13488b74.png)

**Comment by ivantcholakov** [comment]
![Screenshot from 2021-01-09 19-28-50](https://user-images.githubusercontent.com/1438104/104104482-2a760a00-52b1-11eb-963f-e7748f9fa214.png)

**Comment by ivantcholakov** [comment]
![image](https://user-images.githubusercontent.com/1438104/104943417-66e6eb80-59be-11eb-8392-3d89f3e0bbc6.png)
