### ISSUE TITLE
Starter Public Edition 5

### ISSUE THREAD

**Issue by krishnaguragain** [ivantcholakov/starter-public-edition-4#83]
Hi!

Is there any possibility to go for v5 with Codeigniter 4? I can help around in weekend for migrating and working on the new version.

**Comment by ivantcholakov** [comment]
I did not have a look at CodeIgniter 4 yet. But, yeah, why not. What exactly do you want from me? To make a separate repository?

**Comment by ivantcholakov** [comment]
https://github.com/ivantcholakov/starter-public-edition-5

I will start to play with CodeIgniter 4.
